name: Smurf
version: '${project.version}'
main: cn.paper_card.smurf.ThePlugin
api-version: '1.20'
author: Paper99
folia-supported: true

commands:
  smurf:
    permission: smurf.command

permissions:
  smurf.command:
    default: op

depend:
  - Database