name: XiaoHao
version: '${project.version}'
main: cn.paper_card.xiaohao.XiaoHao
api-version: '1.20'
author: Paper99
folia-supported: true

commands:
  xiaohao:
    permission: xiaohao.command

permissions:
  xiaohao.command:
    default: op

depend:
  - Database